### ISSUE TITLE
starting help? + needs git react

### ISSUE THREAD

**Issue by Justinfront** [elsassph/haxe-react-redux#1]
It seems to need git react ( ReactUtil was missing ), so you can't currently install via haxelib, so got react from github, using haxe 3.3.0.
Can you clarify how to run the application, I have been running some traditional react projects but must admit still very much learning and a lot of them have scripts to automagically open the browser or electron.

I tried opening a local browser after following all the instructions.
http://localhost:3000/

but that did not work, maybe I have another react running?  But some advice welcome on basics of running the app.

Justin:haxe-react-redux justinfront$ livereloadx -s bin
2016-11-14 15:17:12 - info:  Config:
2016-11-14 15:17:12 - info:    - mode:   static
2016-11-14 15:17:12 - info:    - port:   35729
2016-11-14 15:17:12 - info:    - filter:
2016-11-14 15:17:12 - info:      1: exclude ".{git,svn}/"
2016-11-14 15:17:12 - info:      2: include "*/"
2016-11-14 15:17:12 - info:      3: include "*.{html,shtml,tmpl,xml,css,js,json,jpeg,jpg,gif,png,ico,cgi,php,py,pl,pm,rb}"
2016-11-14 15:17:12 - info:      4: exclude "*"
2016-11-14 15:17:12 - info:  Enabled static mode.
2016-11-14 15:17:12 - info:  Waiting on port 35729...
2016-11-14 15:17:12 - info:  Watching "/projects/work/reactReduxHaxe/haxe-react-redux/bin"...
2016-11-14 15:18:12 - info:  notify: index.js (0 client) 
2016-11-14 15:37:30 - info:  notify: index.js (0 client) 
2016-11-14 15:40:28 - info:  notify: index.js (0 client)

**Comment by Justinfront** [comment]
Could you add more instructions on starting the app here cheers.
https://github.com/elsassph/haxe-react-redux#building-the-app

**Comment by Justinfront** [comment]
Ah, looked a strange number must have originally tried it with a slash not colon, still very much a flash dev that's been using AIR too much.
http://localhost:35729/

**Comment by elsassph** [comment]
Yes, the readme anticipates on the haxelib release - I didn't want to clutter the doc with that.

I can add the port info but... it's displayed by the server when it starts ;)

**Comment by Justinfront** [comment]
Well perhaps but some of the guys at work are learning traditional React and they did not realize either that was a valid port number.  They were confused by the lack of webpack etc... it would be good to perhaps when you have some time to do a component stack comparisom and explaination, it's perhaps a bit of a mind shift.  Probably no hope for where I work but if you can get on the js geeks radar then sheep will follow and I think you need to really remove all barriers.  
Did you look at Riot, saw a really much simpler todo but apparently it does not scale?? but there is a haxe extern, is there any mileage in adding some haxe magic and improvements to Riot? I just feel that React generally has a lot of boiler plate complexity and dependancy and Riot looked to have a lot less, but maybe all React needs is some haxe like you've done.  Would be nice to get a bit more detail on workings and more different examples like a page menu system, will prob try to get my head round some of your code tomorrow as I can argue theory is all applicable to js react learning.
