### ISSUE TITLE
route behavior

### ISSUE THREAD

**Issue by tbrannam** [elsassph/haxe-react-redux#3]
Perhaps I'm missing a detail, but shouldn't reloading the browser when viewing `/about` - render the about view?  It just returns a 404 in my environment.

**Comment by tbrannam** [comment]
Oh - I need to write the url on the server.   I had expected that livereloadx had this behavior (looks like it doesn't)

**Comment by elsassph** [comment]
Yes it unfortunately doesn't do URL rewriting. 
Needs to be improved.

**Comment by elsassph** [comment]
Adding URL rewriting to `livereloadx` in PR https://github.com/nitoyon/livereloadx/pull/36

**Comment by elsassph** [comment]
`livereloadx` 0.3.1 released with support for URL rewriting 
https://github.com/nitoyon/livereloadx/releases/tag/v0.3.10
