### ISSUE TITLE
Strange autocomplete after updating to haxe react 1.2.0

### ISSUE THREAD

**Issue by djaonourside** [elsassph/haxe-react-redux#6]
Autocomplete in connected component classes shows only build-in compiler metadata instead of methods and props after updating to haxe react 1.2.0. Please take a look a pic. 
![screen](https://cloud.githubusercontent.com/assets/12369638/26805401/72ebf786-4a54-11e7-97b0-b58cd175eb0b.png)

**Comment by elsassph** [comment]
That's a react lib issue, thanks for pointing it out: https://github.com/massiveinteractive/haxe-react/pull/77

**Comment by elsassph** [comment]
Fix is in code-review.

**Comment by elsassph** [comment]
Fixed in haxelib react 1.2.1
